AWSTemplateFormatVersion: '2010-09-09'

Description: Zearch engine stack

Resources:
  IndexQueue:
    Type: AWS::SQS::Queue
    Properties: 
      MessageRetentionPeriod: 86400 # One day retention period
      QueueName: IndexQueue
      ReceiveMessageWaitTimeSeconds: 20
      SqsManagedSseEnabled: false

  SpiderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SpiderRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: SpiderPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
                - sqs:SendMessageBatch
              Resource: !GetAtt IndexQueue.Arn
  EngineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EngineRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: EnginePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:DeleteMessageBatch
              Resource: !GetAtt IndexQueue.Arn
  SpiderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: SpiderInstanceProfile
      Path: /
      Roles: 
        - !Ref SpiderRole
  SpiderLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-0e33e5fdabd319577
      InstanceType: t4g.nano
      IamInstanceProfile: !Ref SpiderInstanceProfile
      UserData: !Base64 |
          #!/bin/bash
          sudo yum update -y
          sudo yum install git -y
          sudo amazon-linux-extras install java-openjdk11 -y
          sudo yum install java-11-devel -y
          cd ~
          git clone https://github.com/zawie/zearch-engine.git
          cd zearch-engine
          make build-crawler
          ./scripts/crawler/main.sh https://en.wikipedia.org/wiki/List_of_most_visited_websites
          

  SpiderAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        - us-west-2a 
        - us-west-2b 
        - us-west-2c
      LaunchConfigurationName: !Ref SpiderLaunchConfiguration
      MinSize: "2"
      MaxSize: "2"
      DesiredCapacity: "2"
